service:
 jenkins:
  conatainer_name: jenkins-ansible
  build:
   context: jenkins-agent-folder
  volume:
   - "$PWD/jenkins:/va/jenkins_home"
  ports:
   - "8080:8080"
  networks:
   - user-defined-network
networks:
 user-defined-network:
  driver: bridge
