services:
  jenkins:
    container_name: jenkins
    image: jenkins-ansible-image
    build:
      context: jenkins-ansible
    ports:
      - "8080:8080"
    volumes:
      - "./jenkins:/var/jenkins_home"
    networks:
      - user-defined-network

networks:
  user-defined-network:
    driver: bridge
